version: '2'

services:
  app:
    build:
      context: ./docker
    container_name: "app"
    ports:
      - "80:80"
    volumes:
      - .:/var/www

  chromedriver:
    image: robcherry/docker-chromedriver
    container_name: "chromedriver"
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
      CHROMEDRIVER_URL_BASE: "/wd/hub"
    security_opt:
      - seccomp:unconfined
